// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// sidebars.js
const sidebars = {
  tutorialSidebar: [
    'intro',                          
    {
      type: 'category',
      label: '01. AI 기본기',
      items: [{ type: 'autogenerated', dirName: '01-fundamentals' }],
    },
    {
      type: 'category',
      label: '02. 소식 & 논문',
      items: [{ type: 'autogenerated', dirName: '02-news-papers' }],
    },
    {
      type: 'category',
      label: '03. 백엔드',
      items: [{ type: 'autogenerated', dirName: '03-backend' }],
    },
    {
      type: 'category',
      label: '04. Tools',
      items: [{ type: 'autogenerated', dirName: '04-tools' }],
    },
    {
      type: 'category',
      label: '05. 프로젝트',
      items: [{ type: 'autogenerated', dirName: '05-projects' }],
    },
    {
      type: 'category',
      label: '06. 기타',
      items: [{ type: 'autogenerated', dirName: '06-etc' }],
    },
  ],
}

export default sidebars;
