// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// sidebars.js
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '01. AI Basics',
      items: [{ type: 'autogenerated', dirName: '01-basics' }],
    },
    {
      type: 'category',
      label: '02. AI News & Papers',
      items: [{ type: 'autogenerated', dirName: '02-news-papers' }],
    },
    {
      type: 'category',
      label: '03. Backend',
      items: [{ type: 'autogenerated', dirName: '03-backend' }],
    },
    {
      type: 'category',
      label: '04. AI Tools',
      items: [{ type: 'autogenerated', dirName: '04-ai-tools' }],
    },
    // {
    //   type: 'category',
    //   label: '05. Projects',
    //   items: [{ type: 'autogenerated', dirName: '05-projects' }],
    // },
    // {
    //   type: 'category',
    //   label: '06. Etc',
    //   items: [{ type: 'autogenerated', dirName: '06-etc' }],
    // },
  ],
}

export default sidebars;
